from django.urls import include, path
from netbox.views.generic import ObjectChangeLogView
from utilities.urls import get_model_urls

from . import models, views

urlpatterns = (
    path('stripe/webhook/', views.StripeWebhookIngressView.as_view(), name='stripe_webhook'),
    path('stripe/webhook/metrics/', views.StripeWebhookMetricsView.as_view(), name='stripe_webhook_metrics'),
    path('cx/', views.CXDashboardView.as_view(), name='cx_dashboard'),
    path('cx/onboarding/', views.CXOnboardingView.as_view(), name='cx_onboarding'),
    path('cx/catalog/', views.CXCatalogView.as_view(), name='cx_catalog'),
    path('cx/customers/<int:pk>/', views.CXCustomerView.as_view(), name='cx_customer'),
    path('cx/manage/<str:model>/add/', views.CXObjectEditView.as_view(), name='cx_add'),
    path('cx/manage/<str:model>/<int:pk>/edit/', views.CXObjectEditView.as_view(), name='cx_edit'),
    path('cx/manage/<str:model>/<int:pk>/delete/', views.CXObjectDeleteView.as_view(), name='cx_delete'),
    path('cx/customers/<int:pk>/charge-now/', views.CXChargeNowView.as_view(), name='cx_charge_now'),
    path('cx/customers/<int:pk>/schedule-payment/', views.CXSchedulePaymentView.as_view(), name='cx_schedule_payment'),
    path(
        'cx/customers/<int:pk>/scheduled-payments/<int:scheduled_payment_pk>/run/',
        views.CXRunScheduledPaymentView.as_view(),
        name='cx_run_scheduled_payment',
    ),
    path(
        'cx/customers/<int:pk>/scheduled-payments/<int:scheduled_payment_pk>/cancel/',
        views.CXCancelScheduledPaymentView.as_view(),
        name='cx_cancel_scheduled_payment',
    ),

    path('accounts/', views.BillingAccountListView.as_view(), name='billingaccount_list'),
    path('accounts/add/', views.BillingAccountEditView.as_view(), name='billingaccount_add'),
    path('accounts/<int:pk>/', views.BillingAccountView.as_view(), name='billingaccount'),
    path('accounts/<int:pk>/', include(get_model_urls('netbox_billing', 'billingaccount')), name='billingaccount'),
    path('accounts/<int:pk>/edit/', views.BillingAccountEditView.as_view(), name='billingaccount_edit'),
    path('accounts/<int:pk>/delete/', views.BillingAccountDeleteView.as_view(), name='billingaccount_delete'),
    path('accounts/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='billingaccount_changelog', kwargs={'model': models.BillingAccount}),

    path('profiles/', views.CustomerProfileListView.as_view(), name='customerprofile_list'),
    path('profiles/add/', views.CustomerProfileEditView.as_view(), name='customerprofile_add'),
    path('profiles/<int:pk>/', views.CustomerProfileView.as_view(), name='customerprofile'),
    path('profiles/<int:pk>/', include(get_model_urls('netbox_billing', 'customerprofile')), name='customerprofile'),
    path('profiles/<int:pk>/edit/', views.CustomerProfileEditView.as_view(), name='customerprofile_edit'),
    path('profiles/<int:pk>/delete/', views.CustomerProfileDeleteView.as_view(), name='customerprofile_delete'),
    path('profiles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='customerprofile_changelog', kwargs={'model': models.CustomerProfile}),

    path('labels/', views.CustomerLabelListView.as_view(), name='customerlabel_list'),
    path('labels/add/', views.CustomerLabelEditView.as_view(), name='customerlabel_add'),
    path('labels/<int:pk>/', views.CustomerLabelView.as_view(), name='customerlabel'),
    path('labels/<int:pk>/', include(get_model_urls('netbox_billing', 'customerlabel')), name='customerlabel'),
    path('labels/<int:pk>/edit/', views.CustomerLabelEditView.as_view(), name='customerlabel_edit'),
    path('labels/<int:pk>/delete/', views.CustomerLabelDeleteView.as_view(), name='customerlabel_delete'),
    path('labels/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='customerlabel_changelog', kwargs={'model': models.CustomerLabel}),

    path('properties/', views.PropertyListView.as_view(), name='property_list'),
    path('properties/add/', views.PropertyEditView.as_view(), name='property_add'),
    path('properties/<int:pk>/', views.PropertyView.as_view(), name='property'),
    path('properties/<int:pk>/', include(get_model_urls('netbox_billing', 'property')), name='property'),
    path('properties/<int:pk>/edit/', views.PropertyEditView.as_view(), name='property_edit'),
    path('properties/<int:pk>/delete/', views.PropertyDeleteView.as_view(), name='property_delete'),
    path('properties/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='property_changelog', kwargs={'model': models.Property}),

    path('units/', views.UnitListView.as_view(), name='unit_list'),
    path('units/add/', views.UnitEditView.as_view(), name='unit_add'),
    path('units/<int:pk>/', views.UnitView.as_view(), name='unit'),
    path('units/<int:pk>/', include(get_model_urls('netbox_billing', 'unit')), name='unit'),
    path('units/<int:pk>/edit/', views.UnitEditView.as_view(), name='unit_edit'),
    path('units/<int:pk>/delete/', views.UnitDeleteView.as_view(), name='unit_delete'),
    path('units/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='unit_changelog', kwargs={'model': models.Unit}),

    path('tariffs/', views.TariffPlanListView.as_view(), name='tariffplan_list'),
    path('tariffs/add/', views.TariffPlanEditView.as_view(), name='tariffplan_add'),
    path('tariffs/<int:pk>/', views.TariffPlanView.as_view(), name='tariffplan'),
    path('tariffs/<int:pk>/', include(get_model_urls('netbox_billing', 'tariffplan')), name='tariffplan'),
    path('tariffs/<int:pk>/edit/', views.TariffPlanEditView.as_view(), name='tariffplan_edit'),
    path('tariffs/<int:pk>/delete/', views.TariffPlanDeleteView.as_view(), name='tariffplan_delete'),
    path('tariffs/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='tariffplan_changelog', kwargs={'model': models.TariffPlan}),

    path('bundles/', views.TariffBundleListView.as_view(), name='tariffbundle_list'),
    path('bundles/add/', views.TariffBundleEditView.as_view(), name='tariffbundle_add'),
    path('bundles/<int:pk>/', views.TariffBundleView.as_view(), name='tariffbundle'),
    path('bundles/<int:pk>/', include(get_model_urls('netbox_billing', 'tariffbundle')), name='tariffbundle'),
    path('bundles/<int:pk>/edit/', views.TariffBundleEditView.as_view(), name='tariffbundle_edit'),
    path('bundles/<int:pk>/delete/', views.TariffBundleDeleteView.as_view(), name='tariffbundle_delete'),
    path('bundles/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='tariffbundle_changelog', kwargs={'model': models.TariffBundle}),

    path('subscriptions/', views.SubscriptionListView.as_view(), name='subscription_list'),
    path('subscriptions/add/', views.SubscriptionEditView.as_view(), name='subscription_add'),
    path('subscriptions/<int:pk>/', views.SubscriptionView.as_view(), name='subscription'),
    path('subscriptions/<int:pk>/', include(get_model_urls('netbox_billing', 'subscription')), name='subscription'),
    path('subscriptions/<int:pk>/edit/', views.SubscriptionEditView.as_view(), name='subscription_edit'),
    path('subscriptions/<int:pk>/delete/', views.SubscriptionDeleteView.as_view(), name='subscription_delete'),
    path('subscriptions/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='subscription_changelog', kwargs={'model': models.Subscription}),

    path('invoices/', views.InvoiceListView.as_view(), name='invoice_list'),
    path('invoices/add/', views.InvoiceEditView.as_view(), name='invoice_add'),
    path('invoices/<int:pk>/', views.InvoiceView.as_view(), name='invoice'),
    path('invoices/<int:pk>/', include(get_model_urls('netbox_billing', 'invoice')), name='invoice'),
    path('invoices/<int:pk>/edit/', views.InvoiceEditView.as_view(), name='invoice_edit'),
    path('invoices/<int:pk>/delete/', views.InvoiceDeleteView.as_view(), name='invoice_delete'),
    path('invoices/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='invoice_changelog', kwargs={'model': models.Invoice}),

    path('invoice-lines/', views.InvoiceLineListView.as_view(), name='invoiceline_list'),
    path('invoice-lines/add/', views.InvoiceLineEditView.as_view(), name='invoiceline_add'),
    path('invoice-lines/<int:pk>/', views.InvoiceLineView.as_view(), name='invoiceline'),
    path('invoice-lines/<int:pk>/', include(get_model_urls('netbox_billing', 'invoiceline')), name='invoiceline'),
    path('invoice-lines/<int:pk>/edit/', views.InvoiceLineEditView.as_view(), name='invoiceline_edit'),
    path('invoice-lines/<int:pk>/delete/', views.InvoiceLineDeleteView.as_view(), name='invoiceline_delete'),
    path('invoice-lines/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='invoiceline_changelog', kwargs={'model': models.InvoiceLine}),

    path('payments/', views.PaymentListView.as_view(), name='payment_list'),
    path('payments/add/', views.PaymentEditView.as_view(), name='payment_add'),
    path('payments/<int:pk>/', views.PaymentView.as_view(), name='payment'),
    path('payments/<int:pk>/', include(get_model_urls('netbox_billing', 'payment')), name='payment'),
    path('payments/<int:pk>/edit/', views.PaymentEditView.as_view(), name='payment_edit'),
    path('payments/<int:pk>/delete/', views.PaymentDeleteView.as_view(), name='payment_delete'),
    path('payments/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='payment_changelog', kwargs={'model': models.Payment}),

    path('scheduled-payments/', views.ScheduledPaymentListView.as_view(), name='scheduledpayment_list'),
    path('scheduled-payments/add/', views.ScheduledPaymentEditView.as_view(), name='scheduledpayment_add'),
    path('scheduled-payments/<int:pk>/', views.ScheduledPaymentView.as_view(), name='scheduledpayment'),
    path('scheduled-payments/<int:pk>/', include(get_model_urls('netbox_billing', 'scheduledpayment')), name='scheduledpayment'),
    path('scheduled-payments/<int:pk>/edit/', views.ScheduledPaymentEditView.as_view(), name='scheduledpayment_edit'),
    path('scheduled-payments/<int:pk>/delete/', views.ScheduledPaymentDeleteView.as_view(), name='scheduledpayment_delete'),
    path(
        'scheduled-payments/<int:pk>/changelog/',
        ObjectChangeLogView.as_view(),
        name='scheduledpayment_changelog',
        kwargs={'model': models.ScheduledPayment},
    ),

    path('documents/', views.CustomerDocumentListView.as_view(), name='customerdocument_list'),
    path('documents/add/', views.CustomerDocumentEditView.as_view(), name='customerdocument_add'),
    path('documents/<int:pk>/', views.CustomerDocumentView.as_view(), name='customerdocument'),
    path('documents/<int:pk>/', include(get_model_urls('netbox_billing', 'customerdocument')), name='customerdocument'),
    path('documents/<int:pk>/edit/', views.CustomerDocumentEditView.as_view(), name='customerdocument_edit'),
    path('documents/<int:pk>/delete/', views.CustomerDocumentDeleteView.as_view(), name='customerdocument_delete'),
    path('documents/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='customerdocument_changelog', kwargs={'model': models.CustomerDocument}),

    path('communications/', views.CustomerCommunicationListView.as_view(), name='customercommunication_list'),
    path('communications/add/', views.CustomerCommunicationEditView.as_view(), name='customercommunication_add'),
    path('communications/<int:pk>/', views.CustomerCommunicationView.as_view(), name='customercommunication'),
    path('communications/<int:pk>/', include(get_model_urls('netbox_billing', 'customercommunication')), name='customercommunication'),
    path('communications/<int:pk>/edit/', views.CustomerCommunicationEditView.as_view(), name='customercommunication_edit'),
    path('communications/<int:pk>/delete/', views.CustomerCommunicationDeleteView.as_view(), name='customercommunication_delete'),
    path('communications/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='customercommunication_changelog', kwargs={'model': models.CustomerCommunication}),

    path('notes/', views.CustomerNoteListView.as_view(), name='customernote_list'),
    path('notes/add/', views.CustomerNoteEditView.as_view(), name='customernote_add'),
    path('notes/<int:pk>/', views.CustomerNoteView.as_view(), name='customernote'),
    path('notes/<int:pk>/', include(get_model_urls('netbox_billing', 'customernote')), name='customernote'),
    path('notes/<int:pk>/edit/', views.CustomerNoteEditView.as_view(), name='customernote_edit'),
    path('notes/<int:pk>/delete/', views.CustomerNoteDeleteView.as_view(), name='customernote_delete'),
    path('notes/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='customernote_changelog', kwargs={'model': models.CustomerNote}),

    path('stripe-events/', views.StripeWebhookEventListView.as_view(), name='stripewebhookevent_list'),
    path('stripe-events/add/', views.StripeWebhookEventEditView.as_view(), name='stripewebhookevent_add'),
    path('stripe-events/<int:pk>/', views.StripeWebhookEventView.as_view(), name='stripewebhookevent'),
    path('stripe-events/<int:pk>/', include(get_model_urls('netbox_billing', 'stripewebhookevent')), name='stripewebhookevent'),
    path('stripe-events/<int:pk>/edit/', views.StripeWebhookEventEditView.as_view(), name='stripewebhookevent_edit'),
    path('stripe-events/<int:pk>/delete/', views.StripeWebhookEventDeleteView.as_view(), name='stripewebhookevent_delete'),
    path('stripe-events/<int:pk>/changelog/', ObjectChangeLogView.as_view(), name='stripewebhookevent_changelog', kwargs={'model': models.StripeWebhookEvent}),

)
