# Generated by Django 5.2.11 on 2026-02-19 04:45

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0121_customfield_related_object_filter'),
        ('netbox_billing', '0002_remove_tariffplan_download_mbps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('method', models.CharField(default='credit_card', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('run_at', models.DateTimeField()),
                ('status', models.CharField(default='scheduled', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=128)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=128)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_payments', to='netbox_billing.billingaccount')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_payments', to='netbox_billing.invoice')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'scheduled payment',
                'verbose_name_plural': 'scheduled payments',
                'ordering': ('run_at', 'created'),
            },
            bases=(models.Model,),
        ),
    ]
