from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    summary: str,
    applies_to_versions: str,
    bug_type: str,
    impact: str,
    invoke_when: list[str],
    diagnostic_commands: list[str],
    decision_tree: list[str],
    likely_root_cause: list[str],
    safe_fix: list[str],
    rollback: list[str],
    *,
    fixed_in: str | None = None,
    avoid_when: list[str] | None = None,
    confirmed_hardware: list[str] | None = None,
    likely_hardware: list[str] | None = None,
    not_relevant_on: list[str] | None = None,
    references: list[str] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "tool_name": name,
        "summary": summary,
        "intent_group": "routing_control_plane",
        "applies_to_versions": applies_to_versions,
        "bug_type": bug_type,
        "impact": impact,
        "invoke_when": invoke_when,
        "avoid_when": avoid_when or [],
        "diagnostic_commands": diagnostic_commands,
        "decision_tree": decision_tree,
        "likely_root_cause": likely_root_cause,
        "safe_fix": safe_fix,
        "rollback": rollback,
        "fixed_in": fixed_in,
        "confirmed_hardware": confirmed_hardware or [],
        "likely_hardware": likely_hardware or [],
        "not_relevant_on": not_relevant_on or [],
        "references": references or ["RouterOS 7.18-7.22 changelogs", "RouterOS forum operator reports"],
        "confidence": confidence,
    }


ROUTEROS_ROUTING_SCENARIOS: dict[str, dict[str, Any]] = {
    "diagnose_bgp_instance_model_change_7_20": _tool(
        name="diagnose_bgp_instance_model_change_7_20",
        summary="BGP sessions stay inactive after upgrade because 7.20 requires explicit /routing/bgp/instance state and migration can fail on complex configs.",
        applies_to_versions="7.20+",
        bug_type="behavior_change",
        impact="high",
        invoke_when=[
            "BGP sessions inactive right after 7.20 upgrade",
            "template/session config looks present but no active instance behavior",
            "complex pre-7.20 BGP layout was auto-migrated",
        ],
        diagnostic_commands=[
            "/routing bgp instance print detail",
            "/routing bgp template print detail",
            "/routing bgp connection print detail",
            "/routing route print where belongs-to~\"bgp\"",
        ],
        decision_tree=[
            "If transport to the peer is broken, fix reachability first.",
            "If the break aligns with 7.20 migration and instances/templates look incomplete, treat this as a model-change issue before rewriting filters.",
        ],
        likely_root_cause=[
            "7.20 BGP instance model change with incomplete auto-migration",
            "downgrade or mixed template state corrupting control-plane configuration",
        ],
        safe_fix=[
            "Create or repair explicit /routing/bgp/instance objects.",
            "Re-bind templates and connections to the intended instance/VRF.",
            "Do not downgrade without export/backup on complex BGP nodes.",
        ],
        rollback=[
            "Restore last known-good export before the 7.20 migration if available.",
        ],
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR", "RB5009"],
    ),
    "diagnose_bgp_filter_not_rejecting_routes": _tool(
        name="diagnose_bgp_filter_not_rejecting_routes",
        summary="v7 BGP filter chain reject rules do not stop acceptance because input.accept-* gates run first and default behavior is accept.",
        applies_to_versions="7.18+",
        bug_type="config_pattern",
        impact="high",
        invoke_when=[
            "BGP filter contains reject rules but routes are still learned",
            "full table or unwanted prefixes still appear after v6 to v7 migration",
            "operator expects v6-style chain semantics",
        ],
        diagnostic_commands=[
            "/routing bgp template print detail",
            "/routing filter rule print detail",
            "/routing route print where belongs-to~\"bgp\"",
        ],
        decision_tree=[
            "If the peer is not sending the routes, this tool is not relevant.",
            "If routes are learned despite reject rules, inspect input.accept-* and default action semantics before blaming the peer.",
        ],
        likely_root_cause=[
            "RouterOS v7 BGP accept gating semantics differ from v6 expectations",
        ],
        safe_fix=[
            "Use input.accept-* to constrain acceptance before the chain when appropriate.",
            "Review chain defaults and rule order with v7 semantics in mind.",
        ],
        rollback=[
            "Revert filter changes if you accidentally drop required routes.",
        ],
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR", "RB5009"],
    ),
    "diagnose_bgp_output_not_cleaned_after_restart": _tool(
        name="diagnose_bgp_output_not_cleaned_after_restart",
        summary="Stale BGP output routes persist after restart or flap, causing re-advertisement and route-leak behavior.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "BGP output table still advertises stale routes after session restart",
            "route reflector or edge peer re-announces withdrawn state after bounce",
            "issue clears only after full process restart or version change",
        ],
        diagnostic_commands=[
            "/routing bgp advertisements print",
            "/routing bgp connection print detail",
            "/routing route print where belongs-to~\"bgp\"",
            "/log print where message~\"bgp\"",
        ],
        decision_tree=[
            "If the peer is replaying stale routes, inspect both sides before assuming local output-cache bug.",
            "If local advertisements survive a flap incorrectly on 7.18-7.21, treat this as the known bug.",
        ],
        likely_root_cause=["BGP output cleanup bug prior to 7.22"],
        safe_fix=["Upgrade to 7.22 or later.", "Use a manual session reset as short-term workaround."],
        rollback=["Return to prior known-good image if upgrade is not yet approved."],
        fixed_in="7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR route reflectors"],
    ),
    "diagnose_bgp_update_not_sent_on_prepend_change": _tool(
        name="diagnose_bgp_update_not_sent_on_prepend_change",
        summary="Changing output.default-prepend does not trigger UPDATE to peers, so traffic-engineering changes are silently ignored until reset.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "Changed default-prepend but peer path selection did not change",
            "no UPDATE seen after TE policy edit",
            "manual session reset makes the change appear",
        ],
        diagnostic_commands=[
            "/routing bgp template print detail",
            "/routing bgp advertisements print",
            "/routing bgp connection print status",
        ],
        decision_tree=[
            "If the peer rejects the route, inspect policy and upstream import first.",
            "If the change only takes effect after a reset on affected versions, this matches the known bug.",
        ],
        likely_root_cause=["BGP UPDATE not emitted on default-prepend change before 7.22"],
        safe_fix=["Upgrade to 7.22 or later.", "Use a manual session reset as temporary workaround."],
        rollback=["Remove temporary prepend changes if they were staged for testing only."],
        fixed_in="7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR", "RB edge routers"],
    ),
    "diagnose_bgp_ignore_as_path_len_not_working": _tool(
        name="diagnose_bgp_ignore_as_path_len_not_working",
        summary="ignore-as-path-len has no effect, so AS-path still drives best-path and breaks intended MED/local-pref engineering.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "ignore-as-path-len is enabled but best-path still tracks AS-path length",
            "MED/local-pref engineering appears ignored",
            "behavior changes only after upgrade to 7.22 or peer reset",
        ],
        diagnostic_commands=[
            "/routing bgp template print detail",
            "/routing route print detail where dst-address=<prefix>",
            "/routing bgp advertisements print",
        ],
        decision_tree=[
            "If local-pref or filter policy differs between peers, normalize policy first.",
            "If AS-path still wins despite ignore-as-path-len on affected versions, treat this as the bug.",
        ],
        likely_root_cause=["ignore-as-path-len ineffective prior to 7.22"],
        safe_fix=["Upgrade to 7.22 or later.", "Use manual policy workarounds or reset expectations on older releases."],
        rollback=["Remove workaround policy when software is fixed."],
        fixed_in="7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR"],
    ),
    "diagnose_bgp_vrf_parameter_missing_after_upgrade": _tool(
        name="diagnose_bgp_vrf_parameter_missing_after_upgrade",
        summary="BGP template/connection loses VRF binding after upgrade from pre-7.20, leaking routes into main.",
        applies_to_versions="7.20-7.20.5",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "BGP routes unexpectedly appear in main after upgrade",
            "VRF-bound peer/template lost its routing-table association",
            "upgrade from pre-7.20 preceded the leak",
        ],
        diagnostic_commands=[
            "/routing bgp template print detail",
            "/routing table print detail",
            "/routing route print detail where belongs-to~\"bgp\"",
        ],
        decision_tree=[
            "If the route leak existed before the upgrade, this tool is probably not the answer.",
            "If VRF binding is missing specifically after 7.20 migration, prioritize this bug.",
        ],
        likely_root_cause=["VRF parameter missing on BGP objects after upgrade"],
        safe_fix=["Upgrade to 7.20.6 or later.", "Reapply explicit VRF/routing-table bindings to affected templates and peers."],
        rollback=["Restore pre-upgrade export if available and safe."],
        fixed_in="7.20.6",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR"],
    ),
    "diagnose_bgp_ecmp_multipath_behavior": _tool(
        name="diagnose_bgp_ecmp_multipath_behavior",
        summary="BGP ECMP behavior is inconsistent before 7.22; 7.22 adds explicit numeric multipath on the instance for cleaner dual-uplink design.",
        applies_to_versions="7.18-7.22",
        bug_type="feature_enablement",
        impact="high",
        invoke_when=[
            "dual BGP uplinks should load-share but only one path wins",
            "operator is designing or debugging ECMP on RouterOS v7",
            "pre-7.22 multipath behavior feels inconsistent",
        ],
        diagnostic_commands=[
            "/routing bgp instance print detail",
            "/routing route print detail where dst-address=0.0.0.0/0",
            "/routing bgp connection print status",
        ],
        decision_tree=[
            "If you need deterministic ECMP design guidance, prefer this tool over generic BGP session tools.",
            "If the network is on pre-7.22, set expectations carefully because the cleaner numeric multipath control is new in 7.22.",
        ],
        likely_root_cause=[
            "Pre-7.22 BGP multipath behavior not matching expected ECMP design",
            "Instance multipath not configured in 7.22+",
        ],
        safe_fix=[
            "On 7.22+, configure instance multipath explicitly.",
            "Validate equal-policy conditions across candidate paths.",
        ],
        rollback=["Revert multipath changes if traffic distribution creates asymmetry or firewall state issues."],
        fixed_in="added in 7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR edge routers"],
    ),
    "diagnose_ospf_loopback_redistribution_external_lsa": _tool(
        name="diagnose_ospf_loopback_redistribution_external_lsa",
        summary="redistribute=connected causes loopbacks to appear as Type-5 external LSAs, which can lose to internal routes and produce wrong next-hop choice.",
        applies_to_versions="7.18+",
        bug_type="config_pattern",
        impact="high",
        invoke_when=[
            "loopback reachability exists but path selection is wrong in OSPF",
            "connected redistribution is used for loopbacks",
            "external LSAs appear for prefixes that should be internal",
        ],
        diagnostic_commands=[
            "/routing ospf instance print detail",
            "/routing ospf interface-template print detail",
            "/routing route print detail where dst-address=<loopback-prefix>",
        ],
        decision_tree=[
            "If loopbacks are already injected by interface-template, this tool is not the fit.",
            "If redistribute=connected is being used for loopbacks, prefer interface-template instead.",
        ],
        likely_root_cause=["Loopbacks injected as Type-5 externals instead of internal OSPF routes"],
        safe_fix=["Advertise loopbacks via interface-template instead of blanket redistribute=connected."],
        rollback=["Reinstate prior OSPF advertisement method if the change affects neighbors unexpectedly."],
        confirmed_hardware=["CCR2004"],
        likely_hardware=["RouterOS OSPF nodes"],
    ),
    "diagnose_ospf_bfd_stuck_init_state": _tool(
        name="diagnose_ospf_bfd_stuck_init_state",
        summary="BFD over OSPF stalls in Init on 7.21/rc2-era code, preventing stable adjacency until BFD is disabled or fixed release is used.",
        applies_to_versions="7.21rc2-7.21",
        bug_type="bug",
        impact="medium",
        invoke_when=[
            "OSPF neighbor stuck in Init with BFD enabled",
            "peer never reaches Full even though transport is up",
            "problem appeared on 7.21rc2/7.21",
        ],
        diagnostic_commands=[
            "/routing ospf neighbor print detail",
            "/routing bfd session print detail",
            "/log print where message~\"ospf|bfd\"",
        ],
        decision_tree=[
            "If basic multicast/unicast reachability is broken, fix that first.",
            "If disabling BFD immediately restores adjacency on affected versions, treat this as the bug.",
        ],
        likely_root_cause=["7.21-era OSPF+BFD regression"],
        safe_fix=["Upgrade to 7.21.1 or later.", "Disable BFD on the OSPF template as a workaround."],
        rollback=["Re-enable BFD after upgrading and validating stable adjacency."],
        fixed_in="7.21.1",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["RouterOS OSPF nodes"],
    ),
    "diagnose_route_not_removed_after_safe_mode": _tool(
        name="diagnose_route_not_removed_after_safe_mode",
        summary="Routes added in safe mode persist after unexpected disconnect, so rollback silently fails on affected versions.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "safe-mode session drops but route changes remain",
            "operator expected rollback after SSH/WinBox disconnect",
            "headend failover behavior changed after a supposedly reverted test",
        ],
        diagnostic_commands=[
            "/ip route print detail",
            "/routing route print detail",
            "/log print where message~\"safe\"",
        ],
        decision_tree=[
            "If the change was committed intentionally, this tool is irrelevant.",
            "If a dropped management session should have reverted routes but did not on 7.18-7.21, this is the bug.",
        ],
        likely_root_cause=["Safe-mode route rollback failure prior to 7.22"],
        safe_fix=["Upgrade to 7.22 or later.", "Do not trust safe mode alone for route testing on affected versions."],
        rollback=["Manually remove the staged routes and verify active/default route state."],
        fixed_in="7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["CCR headends"],
    ),
    "diagnose_routes_with_low_scope_broken": _tool(
        name="diagnose_routes_with_low_scope_broken",
        summary="Static routes with scope 1-9 fail to install or resolve gateways correctly on affected versions.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="medium",
        invoke_when=[
            "static route exists but never installs in FIB",
            "gateway resolution breaks with low scope values",
            "boundary scope values 1-9 are in use",
        ],
        diagnostic_commands=[
            "/ip route print detail",
            "/routing route print detail where dst-address=<prefix>",
            "/log print where message~\"route\"",
        ],
        decision_tree=[
            "If the gateway itself is unreachable, fix that first.",
            "If only low-scope routes misbehave on affected versions, treat this as the scope bug.",
        ],
        likely_root_cause=["Low-scope route installation bug prior to 7.22"],
        safe_fix=["Upgrade to 7.22 or later.", "Use scope 10+ temporarily if the design allows it."],
        rollback=["Restore the original scope after upgrade if it was intentionally chosen."],
        fixed_in="7.22",
        confirmed_hardware=["CCR2004"],
        likely_hardware=["RouterOS routers"],
    ),
    "diagnose_bgp_default_route_ospf_redistribution_leak": _tool(
        name="diagnose_bgp_default_route_ospf_redistribution_leak",
        summary="Static fallback default leaks into OSPF alongside BGP default because redistribution is not gated on origin.",
        applies_to_versions="7.18+",
        bug_type="config_pattern",
        impact="high",
        invoke_when=[
            "OSPF peers see multiple default routes with different origin intent",
            "static fallback default should stay local but leaks into OSPF",
            "route origin filtering was not explicitly designed",
        ],
        diagnostic_commands=[
            "/routing ospf instance print detail",
            "/routing filter rule print detail",
            "/routing route print detail where dst-address=0.0.0.0/0",
        ],
        decision_tree=[
            "If only one default exists locally, this tool may be overfitting.",
            "If both BGP and static fallback defaults exist, explicitly gate OSPF redistribution by route origin.",
        ],
        likely_root_cause=["Redistribution policy does not distinguish fallback static default from intended advertised default"],
        safe_fix=["Use originate-default=if-installed where appropriate.", "Filter redistribution based on route origin and intended failover design."],
        rollback=["Revert filter/originate-default changes if downstream OSPF domain loses required default reachability."],
        confirmed_hardware=["CCR2004"],
        likely_hardware=["RouterOS edge and core routers"],
    ),
    "diagnose_check_gateway_state_logging": _tool(
        name="diagnose_check_gateway_state_logging",
        summary="check-gateway failover does not trip as expected because probes use wrong path, are blocked, or rely on ARP in unsuitable designs. 7.22 adds clearer logging.",
        applies_to_versions="7.18+",
        bug_type="config_pattern",
        impact="high",
        invoke_when=[
            "failover route never deactivates even when upstream is dead",
            "check-gateway is configured but probes are misleading",
            "operator needs pre-7.22 workaround or 7.22 logging guidance",
        ],
        diagnostic_commands=[
            "/ip route print detail where check-gateway!=\"\"",
            "/log print where message~\"gateway|route\"",
            "/ping <target> routing-table=<table>",
        ],
        decision_tree=[
            "If the probe target is reachable through the wrong uplink, the failover design is wrong even if RouterOS is behaving correctly.",
            "On PPPoE and blocked-ICMP paths, use netwatch or better targets instead of assuming check-gateway alone is enough.",
        ],
        likely_root_cause=[
            "Probe target chosen badly for the failover design",
            "ICMP/ARP method does not match the access medium",
            "pre-7.22 visibility makes diagnosis harder without explicit logging",
        ],
        safe_fix=[
            "Choose a probe target that is only reachable through the intended uplink.",
            "Use netwatch or alternate failover logic where check-gateway is the wrong primitive.",
            "Use 7.22 logging to verify route-state transitions.",
        ],
        rollback=["Return to previous failover logic if new probe policy creates flaps."],
        confirmed_hardware=["CCR2004"],
        likely_hardware=["RouterOS edge routers"],
    ),
}
