from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    summary: str,
    applies_to_versions: str,
    bug_type: str,
    impact: str,
    invoke_when: list[str],
    diagnostic_commands: list[str],
    decision_tree: list[str],
    likely_root_cause: list[str],
    safe_fix: list[str],
    rollback: list[str],
    *,
    fixed_in: str | None = None,
    avoid_when: list[str] | None = None,
    confirmed_hardware: list[str] | None = None,
    likely_hardware: list[str] | None = None,
    not_relevant_on: list[str] | None = None,
    references: list[str] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "tool_name": name,
        "summary": summary,
        "intent_group": "platform_hardware",
        "applies_to_versions": applies_to_versions,
        "bug_type": bug_type,
        "impact": impact,
        "invoke_when": invoke_when,
        "avoid_when": avoid_when or [],
        "diagnostic_commands": diagnostic_commands,
        "decision_tree": decision_tree,
        "likely_root_cause": likely_root_cause,
        "safe_fix": safe_fix,
        "rollback": rollback,
        "fixed_in": fixed_in,
        "confirmed_hardware": confirmed_hardware or [],
        "likely_hardware": likely_hardware or [],
        "not_relevant_on": not_relevant_on or [],
        "references": references or ["RouterOS 7.17-7.22 changelogs", "RouterOS hardware upgrade notes", "WISP operator upgrade runbooks"],
        "confidence": confidence,
    }


ROUTEROS_PLATFORM_SCENARIOS: dict[str, dict[str, Any]] = {
    "diagnose_ccr2004_upgrade_nand_disk_space_failure": _tool(
        name="diagnose_ccr2004_upgrade_nand_disk_space_failure",
        summary="CCR2004 upgrade fails with low disk or null-upgrade errors when jumping from older builds; use the staged path instead of forcing the target release directly.",
        applies_to_versions="pre-7.16.2 start, jumping to 7.20+",
        bug_type="upgrade_path",
        impact="high",
        invoke_when=["ccr2004 upgrade fails for lack of disk space", "null upgrade error", "old ccr2004 is jumping straight to new stable"],
        diagnostic_commands=["/system resource print", "/system package print detail", "/system routerboard print", "/file print"],
        decision_tree=["If the box is not a CCR2004, do not use this tool.", "If the starting point is very old, use staged upgrades before assuming bad NAND."],
        likely_root_cause=["CCR2004 NAND/package layout trap on older starting releases"],
        safe_fix=["Stage through 7.16.2, run /system/routerboard/upgrade, reboot, then stage through 7.18.2 before the final target.", "Have Netinstall ready for stubborn units."],
        rollback=["Return to the last bootable staged version if the final hop fails."],
        confirmed_hardware=["CCR2004"],
    ),
    "diagnose_device_mode_blocking_features_7_17": _tool(
        name="diagnose_device_mode_blocking_features_7_17",
        summary="Device-mode restrictions on newer hardware block features like scheduler, fetch, PPTP, and L2TP until the mode is explicitly relaxed.",
        applies_to_versions="7.17+",
        bug_type="framework",
        impact="high",
        invoke_when=["new hardware cannot run scheduler or fetch", "provisioning script features are blocked", "device mode is home or basic"],
        diagnostic_commands=["/system/device-mode/print", "/system/script print", "/system/scheduler print"],
        decision_tree=["If the feature worked before an upgrade on the same hardware, verify device mode before blaming script syntax.", "If this is bulk provisioning, prefer the newer Netinstall/FlashFig path where available."],
        likely_root_cause=["Restricted device mode on new RouterOS hardware"],
        safe_fix=["Move the device into the intended mode using the supported workflow.", "Plan physical-button or Netinstall-assisted changes for locked-down units."],
        rollback=["Return to the prior mode only if it does not re-break required provisioning features."],
        confirmed_hardware=["new MikroTik hardware shipping on 7.17+"],
    ),
    "diagnose_rb5009_l2mtu_change_7_21": _tool(
        name="diagnose_rb5009_l2mtu_change_7_21",
        summary="RB5009 default L2MTU changed in 7.21; QinQ and tight encapsulation math can change even when the config looks untouched.",
        applies_to_versions="7.21+",
        bug_type="behavior_change",
        impact="medium",
        invoke_when=["rb5009 upgrade changes l2mtu assumptions", "qinq math breaks after 7.21", "encapsulation headroom changed on rb5009"],
        diagnostic_commands=["/interface ethernet print detail", "/interface bridge port print detail", "/interface vlan print detail"],
        decision_tree=["If you are not using RB5009, skip this tool.", "If you rely on precise L2MTU math, verify explicit values instead of trusting defaults."],
        likely_root_cause=["Intentional RB5009 default L2MTU change in 7.21+"],
        safe_fix=["Set explicit L2MTU values if the design depends on the old behavior.", "Re-check QinQ and service VLAN paths after upgrade."],
        rollback=["Restore old explicit L2MTU only if it is still safe for the hardware and design."],
        confirmed_hardware=["RB5009"],
    ),
    "diagnose_poe_firmware_update_power_interruption_7_22": _tool(
        name="diagnose_poe_firmware_update_power_interruption_7_22",
        summary="Upgrading certain PoE boards to 7.22 can briefly power-cycle all PoE-out ports; plan this like a service interruption, not a quiet patch.",
        applies_to_versions="7.22+",
        bug_type="disruptive_action",
        impact="high",
        invoke_when=["poe devices will be upgraded to 7.22", "aps or cpes are powered from the router or switch", "operator wants risk review before upgrading access gear"],
        diagnostic_commands=["/system routerboard print", "/interface ethernet poe print detail", "/log print where message~\"poe|firmware\""],
        decision_tree=["If the device has no PoE-out workload, the risk is lower.", "If APs/cameras/CPEs depend on PoE-out, treat the upgrade as an outage window."],
        likely_root_cause=["PoE controller firmware update causing brief all-port power interruption"],
        safe_fix=["Schedule maintenance.", "Warn downstream AP/CPE stakeholders.", "Upgrade one dependency domain at a time."],
        rollback=["No true rollback for the brief power interruption; the mitigation is planning."],
        confirmed_hardware=["PoE-out RouterBOARDs", "CRS354-48P"],
    ),
    "diagnose_arm64_unbalanced_cpu_load_rps": _tool(
        name="diagnose_arm64_unbalanced_cpu_load_rps",
        summary="arm64 routing boxes can pin one CPU core while others idle; RPS can improve balance without a reboot.",
        applies_to_versions="7.21+",
        bug_type="performance_feature",
        impact="high",
        invoke_when=["one cpu core is pegged on ccr2004 or rb5009", "moderate load is not spread across cores", "operator wants immediate safe performance tuning"],
        diagnostic_commands=["/tool profile", "/system resource cpu print", "/system/resource/irq/rps/print"],
        decision_tree=["If the platform is not arm64, this tool is irrelevant.", "If the bottleneck is crypto or single-threaded control-plane work, RPS may not be the real fix."],
        likely_root_cause=["RPS not enabled on arm64 forwarding path"],
        safe_fix=["Enable RPS on the relevant IRQs and observe CPU distribution.", "Validate latency and throughput after the change."],
        rollback=["Disable RPS if packet path behavior worsens."],
        fixed_in="added in 7.21",
        confirmed_hardware=["CCR2004", "RB5009"],
    ),
    "diagnose_routerboard_firmware_upgrade_required": _tool(
        name="diagnose_routerboard_firmware_upgrade_required",
        summary="RouterOS package upgrades do not auto-upgrade RouterBOARD firmware; leaving firmware behind creates subtle post-upgrade instability and feature drift.",
        applies_to_versions="all versions",
        bug_type="ops_hygiene",
        impact="high",
        invoke_when=["routeros upgraded but routerboard firmware was not", "post-upgrade hardware behavior is weird", "operator wants safe upgrade checklist"],
        diagnostic_commands=["/system package update print", "/system routerboard print"],
        decision_tree=["If current-firmware and upgrade-firmware differ, do not call the upgrade complete.", "If the box is remote and sensitive, schedule the extra reboot deliberately."],
        likely_root_cause=["RouterBOARD firmware left behind after RouterOS upgrade"],
        safe_fix=["Run /system/routerboard/upgrade and reboot in a maintenance window."],
        rollback=["Keep the pre-upgrade export and package files in case hardware firmware exposes another bug."],
        confirmed_hardware=["CCR2004", "RB5009", "L009", "general RouterBOARD"],
    ),
    "diagnose_local_package_mirror_upgrade": _tool(
        name="diagnose_local_package_mirror_upgrade",
        summary="Local package mirrors help NATed or offline fleets upgrade safely, but architecture mismatches and bad mirror hygiene break upgrades in non-obvious ways.",
        applies_to_versions="7.17+",
        bug_type="fleet_ops",
        impact="high",
        invoke_when=["building a local package mirror", "nated fleet upgrade plan", "offline upgrade source"],
        diagnostic_commands=["/system package local-update print", "/system resource print", "/tool fetch print"],
        decision_tree=["If the fleet can reach official update channels cleanly, this tool may be unnecessary.", "If architecture or package-set mismatch exists, fix that before trusting the mirror."],
        likely_root_cause=["Bad local mirror structure", "wrong architecture packages", "stale or incomplete mirror content"],
        safe_fix=["Mirror only the right packages per architecture.", "Validate one test device before broad rollout."],
        rollback=["Revert the fleet to direct package install if the mirror path is untrusted."],
        confirmed_hardware=["mixed RouterBOARD fleets"],
    ),
    "diagnose_l009_arm64_migration_path": _tool(
        name="diagnose_l009_arm64_migration_path",
        summary="L009 ARM64 migration is opt-in and effectively irreversible without Netinstall; treat it like a platform migration, not a normal package update.",
        applies_to_versions="7.22+",
        bug_type="migration",
        impact="medium",
        invoke_when=["l009 arm64 migration planning", "want containers or arm64 features on l009", "operator is considering the 7.22 migration path"],
        diagnostic_commands=["/system resource print", "/system package print", "/system routerboard print"],
        decision_tree=["If the goal is just a normal upgrade, do not trigger ARM64 migration casually.", "If the box is remote, have a real recovery path first."],
        likely_root_cause=["Treating ARM64 migration as a reversible normal upgrade"],
        safe_fix=["Plan Netinstall-backed migration with backups and explicit rollout.", "Do not do this first on a critical production edge."],
        rollback=["Rollback requires Netinstall and planning; do not assume a simple downgrade path."],
        confirmed_hardware=["L009"],
    ),
    "diagnose_crs3xx_switch_marvell_firmware_7_22": _tool(
        name="diagnose_crs3xx_switch_marvell_firmware_7_22",
        summary="7.22 updates the CRS3xx Marvell switch driver and restores useful switch-cpu counter visibility, which helps validate hardware-forwarding vs CPU-punted traffic.",
        applies_to_versions="7.22+",
        bug_type="platform_fix",
        impact="medium",
        invoke_when=["crs3xx switch-cpu counters are missing", "need better visibility into cpu-punted traffic", "evaluating 7.22 benefits on crs3xx"],
        diagnostic_commands=["/interface ethernet switch print detail", "/interface ethernet switch port print stats", "/interface bridge port print detail"],
        decision_tree=["If the box is not CRS3xx, skip this tool.", "If you need better hardware-offload visibility, this is a legitimate 7.22 reason to upgrade access switches."],
        likely_root_cause=["Older Marvell switch driver behavior on CRS3xx"],
        safe_fix=["Upgrade to 7.22+ on the eligible CRS3xx after normal switch change controls."],
        rollback=["Return to the prior switch package if 7.22 introduces unrelated regressions."],
        fixed_in="7.22",
        confirmed_hardware=["CRS3xx"],
    ),
    "diagnose_upgrade_channel_strategy_wisp": _tool(
        name="diagnose_upgrade_channel_strategy_wisp",
        summary="WISP channel strategy guide: keep headends conservative and access edges more current instead of auto-upgrading everything together.",
        applies_to_versions="all versions",
        bug_type="strategy",
        impact="high",
        invoke_when=["which channel should we run", "headend vs access upgrade policy", "safe 7.22.1 rollout strategy"],
        diagnostic_commands=["/system package update print", "/system resource print"],
        decision_tree=["If the question is about fleet strategy rather than a bug, use this tool.", "Do not auto-upgrade production headends just because access edges are stable on a newer release."],
        likely_root_cause=["Unsafe one-channel-fits-all upgrade strategy"],
        safe_fix=["Keep headends on the most conservative proven release for that role.", "Use newer stable on access only after role-specific validation.", "Never enable blind production auto-upgrade."],
        rollback=["Revert channel choice and staged rollout plan if validation fails."],
        confirmed_hardware=["CCR2004", "RB5009", "CRS access", "L009"],
    ),
    "diagnose_protected_routerboot_flagging": _tool(
        name="diagnose_protected_routerboot_flagging",
        summary="Protected RouterBOOT state can block bootloader changes and recovery procedures; do not discover this for the first time during a failed maintenance window.",
        applies_to_versions="7.17+",
        bug_type="security_framework",
        impact="medium",
        invoke_when=["routerboot flagged yes", "bootloader change blocked", "recovery/reset procedure is unexpectedly blocked"],
        diagnostic_commands=["/system routerboard print", "/system/device-mode/print"],
        decision_tree=["If flagged is not set, do not use this tool.", "If recovery planning matters, verify protected state before the outage window."],
        likely_root_cause=["Protected RouterBOOT / flagged state"],
        safe_fix=["Use the supported physical-button or Netinstall workflow to clear the protected path when appropriate."],
        rollback=["Do not change RouterBOOT state casually; document the recovery path first."],
        confirmed_hardware=["newer RouterBOARD platforms"],
    ),
}


def scenario_tool_names() -> list[str]:
    return list(ROUTEROS_PLATFORM_SCENARIOS.keys())
