from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    summary: str,
    applies_to_versions: str,
    bug_type: str,
    impact: str,
    invoke_when: list[str],
    diagnostic_commands: list[str],
    decision_tree: list[str],
    likely_root_cause: list[str],
    safe_fix: list[str],
    rollback: list[str],
    *,
    fixed_in: str | None = None,
    avoid_when: list[str] | None = None,
    confirmed_hardware: list[str] | None = None,
    likely_hardware: list[str] | None = None,
    not_relevant_on: list[str] | None = None,
    references: list[str] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "tool_name": name,
        "summary": summary,
        "intent_group": "wireless_access",
        "applies_to_versions": applies_to_versions,
        "bug_type": bug_type,
        "impact": impact,
        "invoke_when": invoke_when,
        "avoid_when": avoid_when or [],
        "diagnostic_commands": diagnostic_commands,
        "decision_tree": decision_tree,
        "likely_root_cause": likely_root_cause,
        "safe_fix": safe_fix,
        "rollback": rollback,
        "fixed_in": fixed_in,
        "confirmed_hardware": confirmed_hardware or [],
        "likely_hardware": likely_hardware or [],
        "not_relevant_on": not_relevant_on or [],
        "references": references or ["RouterOS WiFi changelogs", "CAPsMAN operator notes", "wifi-qcom field reports"],
        "confidence": confidence,
    }


ROUTEROS_WIRELESS_SCENARIOS: dict[str, dict[str, Any]] = {
    "diagnose_wireless_driver_package_selection": _tool(
        name="diagnose_wireless_driver_package_selection",
        summary="Decision-gate tool for choosing between wireless, wifi-qcom-ac, and wifi-qcom based on feature support and device family.",
        applies_to_versions="7.13+",
        bug_type="reference",
        impact="high",
        invoke_when=[
            "driver package is unclear",
            "CAPsMAN capability gap is unclear",
            "mixed ac and ax fleet needs feature matrix",
        ],
        diagnostic_commands=[
            "/system package print",
            "/interface wifi print detail",
            "/caps-man manager print detail",
            "/interface wifi cap print detail",
        ],
        decision_tree=[
            "If the AP uses wifi-qcom-ac, do not expect on-capsman forwarding or central VLAN datapath.",
            "If the AP uses wifi-qcom on supported versions, evaluate local vs centralized forwarding based on throughput and topology goals.",
            "If the AP uses legacy wireless, use CAPsMAN v1 logic and do not assume v2 config applies.",
        ],
        likely_root_cause=[
            "Wrong mental model for driver/package capability",
            "Mixed-driver fleet treated like one uniform CAPsMAN domain",
        ],
        safe_fix=[
            "Choose the driver package first, then choose the matching CAPsMAN model.",
            "Keep ac and ax expectations separate unless the package matrix explicitly supports the feature.",
        ],
        rollback=["Revert package or controller migration only with backup/export in hand."],
        confirmed_hardware=["cAP ac", "wAP ac", "hAP ax2", "cAP ax"],
        likely_hardware=["mixed MikroTik WiFi fleets"],
    ),
    "diagnose_wifi_qcom_ac_capsman_forwarding_not_supported": _tool(
        name="diagnose_wifi_qcom_ac_capsman_forwarding_not_supported",
        summary="wifi-qcom-ac never supports on-capsman forwarding; data-channel errors on cAP ac and wAP ac are architecture limits, not fixable bugs.",
        applies_to_versions="all versions",
        bug_type="permanent_limit",
        impact="high",
        invoke_when=[
            "data channel not supported on cAP ac or wAP ac",
            "wifi-qcom-ac AP is expected to central-forward traffic",
            "operator wants CAPsMAN VLAN handling on ac device",
        ],
        diagnostic_commands=[
            "/system package print",
            "/interface wifi cap print detail",
            "/interface wifi datapath print detail",
        ],
        decision_tree=[
            "If the device is ax and on wifi-qcom, use the version-gate tool instead.",
            "If the device is wifi-qcom-ac, stop trying to force on-capsman forwarding.",
        ],
        likely_root_cause=["wifi-qcom-ac driver architecture limitation"],
        safe_fix=[
            "Use local-forwarding on the AP.",
            "Configure VLAN handling locally per AP bridge and access/trunk policy.",
        ],
        rollback=["Remove unsupported datapath settings from the controller."],
        confirmed_hardware=["cAP ac", "wAP ac"],
        not_relevant_on=["wifi-qcom ax devices", "legacy wireless package"],
    ),
    "diagnose_wifi_qcom_capsman_forwarding_version_gate": _tool(
        name="diagnose_wifi_qcom_capsman_forwarding_version_gate",
        summary="wifi-qcom on-capsman forwarding is version-gated; 7.18-7.20 lack the later enablement and centralized forwarding still carries throughput tradeoffs.",
        applies_to_versions="7.18-7.20",
        bug_type="version_gate",
        impact="high",
        invoke_when=[
            "ax CAP joins but on-capsman forwarding fails",
            "operator expects centralized datapath on 7.20 or earlier",
            "throughput is capped badly with on-capsman forwarding",
        ],
        diagnostic_commands=[
            "/system package print",
            "/interface wifi cap print detail",
            "/interface wifi datapath print detail",
        ],
        decision_tree=[
            "If the fleet is wifi-qcom-ac, use the permanent-limit tool instead.",
            "If the fleet is ax on 7.18-7.20, treat centralized forwarding expectations as version-gated.",
        ],
        likely_root_cause=["wifi-qcom centralized forwarding not available or not mature on pre-7.21 builds"],
        safe_fix=["Upgrade to 7.21+ if centralized forwarding is truly required.", "Prefer local-forwarding if throughput and simplicity matter more."],
        rollback=["Revert to local-forwarding if centralized path causes poor performance."],
        fixed_in="enabled in 7.21",
        confirmed_hardware=["hAP ax2", "cAP ax"],
    ),
    "diagnose_ios_cannot_connect_capsman_7_22": _tool(
        name="diagnose_ios_cannot_connect_capsman_7_22",
        summary="iOS hangs at password entry on 7.22/7.22.1 when interworking.realms-raw is set, triggering unintended Passpoint interpretation.",
        applies_to_versions="7.22-7.22.1",
        bug_type="active_bug",
        impact="high",
        invoke_when=[
            "iOS sees SSID but never completes join",
            "password prompt loops or hangs with no useful logs",
            "CAPsMAN v2 config includes interworking realms-raw",
        ],
        diagnostic_commands=[
            "/interface wifi configuration print detail",
            "/log print where message~\"wifi|wpa|eap\"",
        ],
        decision_tree=[
            "If only one AP has the problem, confirm config parity first.",
            "If iOS clients fail with 7.22-era CAPsMAN and realms-raw is set, use the known workaround before deeper certificate guesses.",
        ],
        likely_root_cause=["7.22 Passpoint/interworking parsing bug for iOS clients"],
        safe_fix=["Unset interworking.realms-raw on the affected configuration.", "Re-test immediately; reboot is not required."],
        rollback=["Restore the field only if Passpoint behavior is intentionally required and validated."],
        fixed_in="not fixed as of 7.22.1",
        confirmed_hardware=["wifi-qcom", "CAPsMAN v2 fleets"],
    ),
    "diagnose_capsman_v1_to_v2_migration_traps": _tool(
        name="diagnose_capsman_v1_to_v2_migration_traps",
        summary="CAPsMAN v1 and v2 are parallel systems; config does not auto-convert, and mixed ac+ax fleets require deliberate split-brain design.",
        applies_to_versions="7.13+",
        bug_type="design_guide",
        impact="high",
        invoke_when=[
            "migrating from /caps-man to /interface/wifi",
            "mixed ac and ax fleet exists",
            "operator assumes old CAPsMAN config should just carry over",
        ],
        diagnostic_commands=[
            "/caps-man manager print detail",
            "/caps-man configuration print detail",
            "/interface wifi configuration print detail",
            "/system package print",
        ],
        decision_tree=[
            "If the fleet is entirely legacy wireless, stay in v1 logic.",
            "If the fleet mixes ac and ax, expect both control planes to exist during transition.",
        ],
        likely_root_cause=["Treating CAPsMAN v1 and v2 as one auto-migrated system"],
        safe_fix=["Run v1 and v2 deliberately in parallel where needed.", "Migrate SSID by SSID and package by package."],
        rollback=["Keep exports of both v1 and v2 configs before migration changes."],
        confirmed_hardware=["mixed cAP ac and cAP ax fleets"],
    ),
    "diagnose_capsman_v2_provisioning_not_applying": _tool(
        name="diagnose_capsman_v2_provisioning_not_applying",
        summary="AP joins controller but no useful config applies because manager is set in the wrong place; a common CAPsMAN v2 provisioning trap.",
        applies_to_versions="7.13+",
        bug_type="config_trap",
        impact="high",
        invoke_when=[
            "AP appears adopted but no SSIDs come up as expected",
            "provisioning exists but configuration.manager is misplaced",
            "operator expects provisioning profile alone to force management mode",
        ],
        diagnostic_commands=[
            "/interface wifi cap print detail",
            "/interface wifi provisioning print detail",
            "/interface wifi configuration print detail",
        ],
        decision_tree=[
            "If the CAP never joins, solve reachability or discovery first.",
            "If the CAP joins but no config lands, inspect manager placement before rewriting datapaths.",
        ],
        likely_root_cause=["configuration.manager set on provisioning profile instead of wifi interface / matching config path"],
        safe_fix=["Set the manager mode and config objects where CAPsMAN v2 actually expects them.", "Re-provision after correcting the object placement."],
        rollback=["Restore prior provisioning rows if the fix breaks healthy APs."],
        confirmed_hardware=["wifi-qcom", "wifi-qcom-ac"],
    ),
    "diagnose_ft_over_ds_ios_incompatibility": _tool(
        name="diagnose_ft_over_ds_ios_incompatibility",
        summary="iOS roaming/connectivity issues with FT happen when ft-over-ds=yes; FT-over-Air is the safer default.",
        applies_to_versions="7.18+",
        bug_type="client_compat",
        impact="high",
        invoke_when=[
            "iOS devices fail to roam or connect cleanly with fast transition enabled",
            "other clients work better than Apple clients",
            "ft-over-ds is enabled",
        ],
        diagnostic_commands=[
            "/interface wifi security print detail",
            "/log print where message~\"ft|roam|wpa\"",
        ],
        decision_tree=[
            "If FT is disabled entirely, this tool is irrelevant.",
            "If Apple behavior is uniquely bad and ft-over-ds=yes, switch to ft-over-air first.",
        ],
        likely_root_cause=["Apple client incompatibility with FT over DS"],
        safe_fix=["Set ft-over-ds=no and keep FT over air.", "Retest roaming without rebooting the fleet."],
        rollback=["Restore prior FT mode if client mix proves otherwise."],
        confirmed_hardware=["Apple client environments"],
    ),
    "diagnose_capsman_v2_vlan_local_forwarding_pattern": _tool(
        name="diagnose_capsman_v2_vlan_local_forwarding_pattern",
        summary="Reference pattern for VLAN-per-SSID with CAPsMAN v2 in local-forwarding mode: controller datapath, AP bridge VLANs, and edge port PVID must all agree.",
        applies_to_versions="7.18+",
        bug_type="pattern",
        impact="high",
        invoke_when=[
            "building WiFi needs VLAN-per-SSID with local-forwarding",
            "SSID is up but clients land on wrong VLAN or no DHCP",
            "operator needs the correct CAPsMAN v2 local-forwarding shape",
        ],
        diagnostic_commands=[
            "/interface wifi datapath print detail",
            "/interface wifi configuration print detail",
            "/interface bridge vlan print detail",
            "/interface bridge port print detail",
        ],
        decision_tree=[
            "If the AP is wifi-qcom-ac and centrally forwarded, stop and use the package-selection and permanent-limit tools first.",
            "If the design goal is resilient campus WiFi, prefer local-forwarding unless there is a strong reason to central-forward.",
        ],
        likely_root_cause=["Datapath, AP bridge VLAN table, and uplink tagging not aligned"],
        safe_fix=["Build SSID-to-VLAN mapping in CAPsMAN v2, then mirror it in the AP bridge VLAN table and uplink port membership.", "Validate one SSID/VLAN end-to-end before scaling."],
        rollback=["Back out one SSID/VLAN mapping at a time."],
        confirmed_hardware=["wifi-qcom", "CAPsMAN v2"],
    ),
    "diagnose_capsman_client_flapping": _tool(
        name="diagnose_capsman_client_flapping",
        summary="Clients flap because of reselect-interval, BSS transition behavior, or MAC-randomization side effects that show up as repeated disconnect/reconnect loops.",
        applies_to_versions="7.18+",
        bug_type="config",
        impact="medium",
        invoke_when=[
            "client repeatedly disconnects and reconnects",
            "IoT devices or phones bounce between APs",
            "roaming assist and identity settings changed recently",
        ],
        diagnostic_commands=[
            "/interface wifi registration-table print detail",
            "/interface wifi configuration print detail",
            "/log print where message~\"disconnect|reconnect|deauth|roam\"",
        ],
        decision_tree=[
            "If only one AP drops all clients, inspect AP health first.",
            "If clients oscillate between healthy APs, inspect reselect and roaming policy before changing RF.",
        ],
        likely_root_cause=["Over-aggressive roaming policy", "IoT/client rejection of BSS transition", "MAC randomization creating repeated identity churn"],
        safe_fix=["Relax reselect interval and roaming-assist settings.", "Disable or soften BSS transition for problem clients."],
        rollback=["Restore prior roaming settings if sticky-client behavior becomes worse."],
        confidence="medium",
    ),
    "diagnose_hap_ax2_2g_radio_broken_7_18": _tool(
        name="diagnose_hap_ax2_2g_radio_broken_7_18",
        summary="hAP ax2 2.4 GHz SSID is visible but clients cannot connect on 7.18.1; a model-specific firmware bug fixed in 7.18.2.",
        applies_to_versions="7.18.1",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "hAP ax2 2.4 GHz is visible but unusable",
            "5 GHz works normally",
            "problem started on 7.18.1",
        ],
        diagnostic_commands=[
            "/system package print",
            "/interface wifi print detail",
            "/log print where message~\"wifi|assoc|auth\"",
        ],
        decision_tree=[
            "If the device is not hAP ax2, this tool is a weak fit.",
            "If only 2.4 GHz is broken on 7.18.1, use the version-specific bug path first.",
        ],
        likely_root_cause=["hAP ax2 7.18.1 2.4 GHz firmware/driver bug"],
        safe_fix=["Upgrade to 7.18.2 or later."],
        rollback=["Roll back to prior known-good image if upgrade path is blocked."],
        fixed_in="7.18.2",
        confirmed_hardware=["hAP ax2"],
    ),
    "diagnose_hotspot_mac_randomization_session_conflict": _tool(
        name="diagnose_hotspot_mac_randomization_session_conflict",
        summary="Hotspot or captive-session workflows break when clients randomize MACs and appear as new sessions on every reconnect.",
        applies_to_versions="7.18+",
        bug_type="behavior",
        impact="medium",
        invoke_when=[
            "hotspot users re-login constantly",
            "session churn tracks phone reconnects or roaming",
            "MAC-randomization is common in the client base",
        ],
        diagnostic_commands=[
            "/ip hotspot active print detail",
            "/ip hotspot host print detail",
            "/log print where message~\"hotspot|cookie|radius\"",
        ],
        decision_tree=[
            "If hotspot is not in use, skip this tool.",
            "If clients look like new devices every reconnect, treat randomized MAC identity as the design problem.",
        ],
        likely_root_cause=["Client MAC randomization breaking hotspot session continuity"],
        safe_fix=["Use cookie/TOTP strategies or RADIUS approaches that do not assume stable MAC identity.", "Avoid relying on MAC alone for persistent session identity."],
        rollback=["Restore previous hotspot auth behavior if new policy locks users out."],
        confidence="medium",
    ),
    "diagnose_legacy_capsman_v1_vlan_config": _tool(
        name="diagnose_legacy_capsman_v1_vlan_config",
        summary="Legacy wireless-package CAPsMAN v1 VLAN behavior breaks after 7.x upgrade because old bridge/master-port assumptions do not auto-convert cleanly.",
        applies_to_versions="7.18+",
        bug_type="config",
        impact="medium",
        invoke_when=[
            "legacy CAPsMAN v1 WLANs lose VLAN behavior after upgrade",
            "master-port era assumptions still exist in the bridge",
            "wireless package remains in use",
        ],
        diagnostic_commands=[
            "/caps-man configuration print detail",
            "/interface bridge port print detail",
            "/interface bridge vlan print detail",
        ],
        decision_tree=[
            "If the fleet is on CAPsMAN v2, use the v2 tools instead.",
            "If legacy wireless package stayed in place through 7.x, verify bridge VLAN conversion explicitly.",
        ],
        likely_root_cause=["Legacy CAPsMAN v1 VLAN config not fully migrated to 7.x bridge model"],
        safe_fix=["Rebuild the bridge VLAN table and port membership explicitly.", "Verify legacy datapath and VLAN settings line up with the new bridge model."],
        rollback=["Keep an export of legacy CAPsMAN config before rebuild."],
        confirmed_hardware=["legacy wireless package fleets"],
    ),
    "design_capsman_community_wifi_roaming_domain": _tool(
        name="design_capsman_community_wifi_roaming_domain",
        summary="Design guide for campus/community WiFi roaming domains over existing IDFs, steering toward local-forwarding and routed building handoff instead of one giant flat L2 domain.",
        applies_to_versions="7.18+",
        bug_type="design_guide",
        impact="high",
        invoke_when=[
            "operator wants walk-around community WiFi across a campus",
            "existing IDFs and SFP uplinks are available",
            "needs CAPsMAN guidance for roaming, DHCP, and PoE AP layout",
        ],
        diagnostic_commands=[
            "/system package print",
            "/interface bridge vlan print detail",
            "/ip address print detail",
            "/interface wifi cap print detail",
        ],
        decision_tree=[
            "If the AP package mix is unclear, run the driver-package selection tool first.",
            "If the environment is mixed ac/ax, design the control plane around local-forwarding and routed uplinks before chasing centralized datapath magic.",
            "If the goal is resilient campus coverage, favor consistent SSID/security with routed building edges over a giant shared broadcast domain.",
        ],
        likely_root_cause=[
            "Trying to solve campus roaming with one fragile flat L2 WiFi domain",
            "Assuming CAPsMAN replaces good VLAN and routing design",
        ],
        safe_fix=[
            "Use a PoE MikroTik access box per IDF where needed for AP power and local AP switching.",
            "Keep SSID/security uniform across campus but local-forward traffic at the AP/building edge.",
            "Hand off guest/community WiFi on a dedicated VLAN per building or block, then route upstream cleanly.",
            "Only use centralized forwarding where the package/hardware path truly supports it and the throughput tradeoff is acceptable.",
        ],
        rollback=["Pilot one building first before campus-wide rollout."],
        confirmed_hardware=["cAP", "cAP ax", "IDF-fed campus WiFi designs"],
    ),
}
