from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    summary: str,
    applies_to_versions: str,
    bug_type: str,
    impact: str,
    invoke_when: list[str],
    diagnostic_commands: list[str],
    decision_tree: list[str],
    likely_root_cause: list[str],
    safe_fix: list[str],
    rollback: list[str],
    *,
    fixed_in: str | None = None,
    avoid_when: list[str] | None = None,
    confirmed_hardware: list[str] | None = None,
    likely_hardware: list[str] | None = None,
    not_relevant_on: list[str] | None = None,
    references: list[str] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "tool_name": name,
        "summary": summary,
        "intent_group": "operations_scripting",
        "applies_to_versions": applies_to_versions,
        "bug_type": bug_type,
        "impact": impact,
        "invoke_when": invoke_when,
        "avoid_when": avoid_when or [],
        "diagnostic_commands": diagnostic_commands,
        "decision_tree": decision_tree,
        "likely_root_cause": likely_root_cause,
        "safe_fix": safe_fix,
        "rollback": rollback,
        "fixed_in": fixed_in,
        "confirmed_hardware": confirmed_hardware or [],
        "likely_hardware": likely_hardware or [],
        "not_relevant_on": not_relevant_on or [],
        "references": references or ["RouterOS 7.x changelogs", "RouterOS scripting and API notes", "WISP automation runbooks"],
        "confidence": confidence,
    }


ROUTEROS_OPS_SCENARIOS: dict[str, dict[str, Any]] = {
    "diagnose_export_missing_sensitive_values": _tool(
        name="diagnose_export_missing_sensitive_values",
        summary="RouterOS v7 exports omit passwords and keys by default, so config backups that rely on plain export can become non-restorable.",
        applies_to_versions="all v7",
        bug_type="behavior_change",
        impact="high",
        invoke_when=["export backup is missing passwords", "oxidized or unimus backup cannot restore secrets", "show-sensitive was not used"],
        diagnostic_commands=["/export", "/export show-sensitive", "/system backup save name=prechange.backup"],
        decision_tree=["If you need a restorable backup, plain export without show-sensitive is not enough.", "If policy forbids plaintext secrets, pair sanitized exports with binary backups intentionally."],
        likely_root_cause=["v7 hide-sensitive export behavior", "automation assuming v6-style export completeness"],
        safe_fix=["Update backup workflow to use show-sensitive where operationally appropriate.", "Keep a binary .backup alongside text export when you need full restore capability."],
        rollback=["Remove plaintext-secret exports from storage if they violate policy."],
    ),
    "diagnose_device_mode_blocking_features_7_17": _tool(
        name="diagnose_device_mode_blocking_features_7_17",
        summary="Newer RouterOS device-mode restrictions can block scheduler, fetch, PPTP, and L2TP, breaking automation unexpectedly.",
        applies_to_versions="7.17+",
        bug_type="security_framework",
        impact="high",
        invoke_when=["scheduler or fetch stopped working on new hardware", "automation breaks after new hardware rollout", "device-mode restrictions block provisioning"],
        diagnostic_commands=["/system/device-mode/print", "/system/script/print", "/system/scheduler/print"],
        decision_tree=["If this is older hardware with open mode, this tool is a weak fit.", "If features are blocked by policy rather than syntax, check device mode first."],
        likely_root_cause=["device-mode restrictions on new hardware"],
        safe_fix=["Move the box into the intended device mode using the supported workflow.", "Use Netinstall/FlashFig path where available for bulk deployment."],
        rollback=["Return the device mode only if it does not re-break provisioning needs."],
        fixed_in="7.22 adds more mode-script paths",
    ),
    "diagnose_date_format_change_7_10": _tool(
        name="diagnose_date_format_change_7_10",
        summary="RouterOS date formatting changed from month-abbrev to ISO-like form, breaking scripts that parse old date strings.",
        applies_to_versions="7.10+",
        bug_type="format_change",
        impact="high",
        invoke_when=["script expects may/10/2023 and gets 2023-05-10", "scheduler or cert parsing broke after upgrade", "log/date parsing broke on older automation"],
        diagnostic_commands=["/system clock print", "/certificate print detail", "/log print where message~\"script|error\""],
        decision_tree=["If the automation never parsed dates, this is not your issue.", "If scripts use month abbreviations or string splits, refactor for the newer format."],
        likely_root_cause=["date format change from pre-7.10 assumptions"],
        safe_fix=["Update scripts to parse ISO-like date strings.", "Avoid brittle string slicing on date output."],
        rollback=["Keep old parsing helper only if you still support pre-7.10 devices."],
    ),
    "diagnose_file_id_format_change_7_21": _tool(
        name="diagnose_file_id_format_change_7_21",
        summary="Internal file IDs changed in 7.21, so scripts that manipulate files by numeric ID instead of name can fail silently.",
        applies_to_versions="7.21+",
        bug_type="format_change",
        impact="medium",
        invoke_when=["script manipulates files by id", "file remove or set broke after 7.21", "automation assumes numeric file handles"],
        diagnostic_commands=["/file print detail", "/log print where message~\"file|script|error\""],
        decision_tree=["If the script already uses file names, skip this tool.", "If the script depends on positional or numeric file IDs, move away from that now."],
        likely_root_cause=["7.21 file ID representation change"],
        safe_fix=["Use file names for set/remove operations.", "Refactor scripts to avoid internal file IDs."],
        rollback=["Keep a compatibility shim only if absolutely necessary for mixed-version fleets."],
        fixed_in="7.22 improves set/remove handling",
    ),
    "diagnose_snmp_bulk_walk_skips_first_oid": _tool(
        name="diagnose_snmp_bulk_walk_skips_first_oid",
        summary="Pre-7.22 SNMP GetBulk can skip the first OID, making dashboards miss the first interface or table row.",
        applies_to_versions="7.18-7.21",
        bug_type="bug",
        impact="high",
        invoke_when=["zabbix or librenms misses first interface", "snmp walk is missing ifIndex 1", "monitoring looks one row short on RouterOS"],
        diagnostic_commands=["/snmp print", "/interface print", "/system resource print"],
        decision_tree=["If the NMS uses GetNext already, this is less likely.", "If the first row is consistently missing on pre-7.22, suspect the GetBulk bug first."],
        likely_root_cause=["SNMP GetBulk first-OID skip bug before 7.22"],
        safe_fix=["Force GetNext in the monitoring system where possible.", "Upgrade RouterOS to 7.22+ on the affected devices."],
        rollback=["Return the NMS poller mode only after confirming fixed RouterOS behavior."],
        fixed_in="7.22",
    ),
    "diagnose_snmp_sysdescr_and_ifspeed_changes_7_22": _tool(
        name="diagnose_snmp_sysdescr_and_ifspeed_changes_7_22",
        summary="7.22 changes sysDescr content and improves high-speed interface reporting, which can break regex-based monitoring assumptions.",
        applies_to_versions="7.22+",
        bug_type="behavior_change",
        impact="medium",
        invoke_when=["sysDescr regex no longer matches after 7.22", "10G interface speed graphs look wrong", "NMS uses ifSpeed instead of ifHighSpeed"],
        diagnostic_commands=["/snmp print", "/interface ethernet print detail"],
        decision_tree=["If the issue is interface presence, use the GetBulk bug tool instead.", "If the issue is metadata parsing or 10G speed math, use this tool."],
        likely_root_cause=["sysDescr format change", "ifSpeed expectations on high-speed ports"],
        safe_fix=["Update sysDescr parsing in monitoring templates.", "Use ifHighSpeed for 10G+ accuracy."],
        rollback=["Pin the old template only if you cannot update the monitoring side immediately."],
    ),
    "diagnose_scripting_loop_control_7_22": _tool(
        name="diagnose_scripting_loop_control_7_22",
        summary="7.22 adds native loop control in RouterOS scripts, reducing ugly flag-variable workarounds and making script intent clearer.",
        applies_to_versions="7.22+",
        bug_type="feature_enablement",
        impact="high",
        invoke_when=["want cleaner RouterOS loop logic", "script uses flag variables to emulate break", "operator is modernizing scripts on 7.22+"],
        diagnostic_commands=["/system script print detail"],
        decision_tree=["If the fleet is not on 7.22+, stick with older script patterns.", "If you are refactoring scripts now, use the native loop controls rather than preserving ugly workarounds."],
        likely_root_cause=["older scripts built before native loop controls existed"],
        safe_fix=["Use :continue, :break, and :exit where they simplify logic."],
        rollback=["Keep the older pattern if you must stay cross-version compatible."],
    ),
    "diagnose_api_sensitive_fields_hidden_7_21": _tool(
        name="diagnose_api_sensitive_fields_hidden_7_21",
        summary="Sensitive fields are hidden from API print responses in 7.21+, which silently breaks Ansible, Terraform, and custom scripts that read secrets back out.",
        applies_to_versions="7.21+",
        bug_type="security_change",
        impact="high",
        invoke_when=["API returns empty secrets", "ansible or terraform reads blank ppp or wg values", "automation depended on print returning sensitive fields"],
        diagnostic_commands=["/ppp secret print detail", "/interface wireguard peers print detail", "/radius print detail"],
        decision_tree=["If the script only pushes config and never reads secrets back, this may not matter.", "If the script validates state by reading secrets from API print, it needs redesign."],
        likely_root_cause=["7.21 API hide-sensitive behavior"],
        safe_fix=["Stop expecting API print to return secrets.", "Refactor automation to manage desired state without round-tripping sensitive values from live print output."],
        rollback=["Remove any insecure workaround that tries to expose secrets broadly just to satisfy the old automation model."],
    ),
    "diagnose_netwatch_vs_check_gateway_design": _tool(
        name="diagnose_netwatch_vs_check_gateway_design",
        summary="Use check-gateway for route failover and Netwatch for script execution; using the wrong primitive causes brittle automation and false expectations.",
        applies_to_versions="7.18+",
        bug_type="design_guide",
        impact="high",
        invoke_when=["operator mixes netwatch and check-gateway roles", "route failover is expected to run scripts automatically", "automation design for failover is unclear"],
        diagnostic_commands=["/ip route print detail", "/tool netwatch print detail", "/log print where message~\"gateway|netwatch\""],
        decision_tree=["If you only need route failover, prefer check-gateway.", "If you need a script to run when state changes, Netwatch is the better fit."],
        likely_root_cause=["wrong tool for the intended failover/automation job"],
        safe_fix=["Separate route liveness from script-runner logic.", "Use Netwatch when you need actions, check-gateway when you need route state."],
        rollback=["Remove duplicate or competing monitors that create looped automation."],
    ),
    "diagnose_scripting_type_conversion_improvements_7_21": _tool(
        name="diagnose_scripting_type_conversion_improvements_7_21",
        summary="7.21 adds better type conversion helpers, so older string-heavy DHCP and address scripts can be simplified and made safer.",
        applies_to_versions="7.21+",
        bug_type="feature_enablement",
        impact="high",
        invoke_when=["old scripts do ugly CIDR or array parsing", "operator wants to modernize RouterOS scripts", "address manipulation scripts are brittle"],
        diagnostic_commands=["/system script print detail"],
        decision_tree=["If the fleet is mixed and includes old versions, keep compatibility in mind.", "If the scripts are 7.21+ only, use the improved conversion helpers."],
        likely_root_cause=["legacy workarounds preserved after newer scripting helpers arrived"],
        safe_fix=["Use the newer conversion helpers for array and address manipulation.", "Reduce brittle string parsing in DHCP or provisioning scripts."],
        rollback=["Keep the older helper path if you must support older releases."],
    ),
    "diagnose_supout_generation_timeout": _tool(
        name="diagnose_supout_generation_timeout",
        summary="7.22 makes supout generation failures explicit with timeout behavior, which changes how operators should wait for or validate support files.",
        applies_to_versions="7.22+",
        bug_type="behavior_change",
        impact="medium",
        invoke_when=["supout file looks incomplete", "support file generation takes a long time", "operator is troubleshooting a busy device and wants a valid rif"],
        diagnostic_commands=["/system sup-output name=test", "/log print where message~\"supout|support\""],
        decision_tree=["If you are on pre-7.22, incomplete supout files may fail silently.", "On 7.22+, allow enough time and check whether timeout was declared explicitly."],
        likely_root_cause=["busy device causes supout generation timeout or incomplete artifact"],
        safe_fix=["Allow several minutes for supout generation on busy boxes.", "Verify completion status before filing a support ticket."],
        rollback=["Retry during a quieter maintenance window if the first capture is incomplete."],
    ),
    "diagnose_logging_improvements_7_22": _tool(
        name="diagnose_logging_improvements_7_22",
        summary="7.22 adds logging features that improve NOC automation, including log-rule comments and script actions tied to log events.",
        applies_to_versions="7.22+",
        bug_type="feature_enablement",
        impact="high",
        invoke_when=["want better log-driven automation", "need cleaner log rule metadata", "building script hooks from RouterOS logs"],
        diagnostic_commands=["/system logging print detail", "/system script print detail", "/log print"],
        decision_tree=["If the fleet is not on 7.22+, do not design around the new logging features yet.", "If you are already on 7.22+, use the native logging improvements instead of external hacks where possible."],
        likely_root_cause=["older logging workflows not updated for 7.22 capabilities"],
        safe_fix=["Use log-rule comments and script actions deliberately.", "Keep log-to-automation behavior narrow and testable."],
        rollback=["Disable any reactive logging script if it becomes noisy or unsafe."],
    ),
    "diagnose_print_follow_on_event_script_runner": _tool(
        name="diagnose_print_follow_on_event_script_runner",
        summary="print follow with on-event lets scripts react to live output streams, which is useful but easy to misuse in noisy environments.",
        applies_to_versions="7.22+",
        bug_type="feature_enablement",
        impact="medium",
        invoke_when=["operator wants live event-driven scripts", "building real-time NOC automation off print follow", "script should react to streaming output"],
        diagnostic_commands=["/log print follow", "/system script print detail"],
        decision_tree=["If polling is enough, do not overcomplicate the design.", "If you truly need event-driven behavior, keep scope tight and test log volume first."],
        likely_root_cause=["new event-driven scripting feature being used without guardrails"],
        safe_fix=["Use print follow on-event only for narrow, tested workflows.", "Stamp timestamps and rate limits into the design."],
        rollback=["Fall back to safer polling if the reactive path becomes noisy or unstable."],
    ),
    "diagnose_fetch_http2_redirect_improvements_7_22": _tool(
        name="diagnose_fetch_http2_redirect_improvements_7_22",
        summary="7.22 improves fetch behavior for redirects and HTTP/2, which matters for webhook, provisioning, and API-calling scripts.",
        applies_to_versions="7.22+",
        bug_type="feature_enablement",
        impact="high",
        invoke_when=["webhook script is flaky across redirects", "provisioning fetch logic is fragile", "operator wants to modernize fetch-heavy automation"],
        diagnostic_commands=["/tool fetch url=<test-url> output=user as-value", "/log print where message~\"fetch|script|error\""],
        decision_tree=["If the script is local-only and never uses fetch, skip this tool.", "If redirect handling or better error reporting matters, use the 7.22 behavior intentionally."],
        likely_root_cause=["older fetch assumptions carried into newer RouterOS versions"],
        safe_fix=["Use the improved fetch behavior and proper on-error handling in 7.22+.", "Validate redirect behavior against the real provisioning endpoints."],
        rollback=["Keep the older fetch path only if the target platform must remain pre-7.22."],
    ),
}


def scenario_tool_names() -> list[str]:
    return list(ROUTEROS_OPS_SCENARIOS.keys())
