from __future__ import annotations

from typing import Any


def _tool(
    name: str,
    summary: str,
    applies_to_versions: str,
    bug_type: str,
    impact: str,
    invoke_when: list[str],
    diagnostic_commands: list[str],
    decision_tree: list[str],
    likely_root_cause: list[str],
    safe_fix: list[str],
    rollback: list[str],
    *,
    fixed_in: str | None = None,
    avoid_when: list[str] | None = None,
    confirmed_hardware: list[str] | None = None,
    likely_hardware: list[str] | None = None,
    not_relevant_on: list[str] | None = None,
    references: list[str] | None = None,
    confidence: str = "high",
) -> dict[str, Any]:
    return {
        "tool_name": name,
        "summary": summary,
        "intent_group": "switching_l2",
        "applies_to_versions": applies_to_versions,
        "bug_type": bug_type,
        "impact": impact,
        "invoke_when": invoke_when,
        "avoid_when": avoid_when or [],
        "diagnostic_commands": diagnostic_commands,
        "decision_tree": decision_tree,
        "likely_root_cause": likely_root_cause,
        "safe_fix": safe_fix,
        "rollback": rollback,
        "fixed_in": fixed_in,
        "confirmed_hardware": confirmed_hardware or [],
        "likely_hardware": likely_hardware or [],
        "not_relevant_on": not_relevant_on or [],
        "references": references or ["RouterOS 7.20-7.22 changelogs", "RouterOS forum operator reports"],
        "confidence": confidence,
    }


ROUTEROS_SWITCHING_SCENARIOS: dict[str, dict[str, Any]] = {
    "diagnose_stp_blocked_after_bridge_mac_change_7_20": _tool(
        name="diagnose_stp_blocked_after_bridge_mac_change_7_20",
        summary="Ports enter blocked state after bridge MAC address changes. Known STP regression in 7.20, fixed in 7.20.2.",
        applies_to_versions="7.20-7.20.1",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "bridge ports unexpectedly move to blocked/discarding after upgrade",
            "topology looks intact but forwarding never resumes",
            "symptoms follow bridge MAC address change or reconvergence event",
        ],
        diagnostic_commands=[
            "/interface bridge print detail",
            "/interface bridge port print detail",
            "/interface bridge monitor <bridge-name>",
            "/log print where message~\"bridge|stp|rstp\"",
        ],
        decision_tree=[
            "If the port is blocked because of a real loop, use loop containment workflow instead.",
            "If blocking appears immediately after upgrade to 7.20.x with no new topology loop, treat this as the regression first.",
        ],
        likely_root_cause=["RouterOS 7.20 STP state handling regression after bridge MAC change"],
        safe_fix=["Upgrade to 7.20.2 or later.", "If urgent, roll back to prior known-good release."],
        rollback=["Restore previous package set and verify port states.", "Re-check RSTP roles after rollback."],
        fixed_in="7.20.2",
        confirmed_hardware=["CRS3xx", "RouterOS bridge devices"],
        likely_hardware=["CCR bridge roles", "RB bridge roles"],
        not_relevant_on=["SwOS-only CRS1xx/2xx"],
    ),
    "diagnose_bridge_forwarding_soft_lock_7_20": _tool(
        name="diagnose_bridge_forwarding_soft_lock_7_20",
        summary="Bridge stops forwarding traffic entirely after upgrade. Known 7.20 soft-lock behavior with delete/recreate workaround.",
        applies_to_versions="7.20",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "interfaces stay link-up but traffic stops traversing the bridge",
            "bridge host learning stalls or becomes nonsensical",
            "delete/recreate bridge is known to restore service temporarily",
        ],
        diagnostic_commands=[
            "/interface bridge print detail",
            "/interface bridge host print",
            "/interface bridge port print detail",
            "/tool profile",
        ],
        decision_tree=[
            "If only one VLAN or one port is broken, use narrower VLAN/PVID tools first.",
            "If the whole bridge datapath freezes on 7.20 while ports remain up, prioritize this regression.",
        ],
        likely_root_cause=["RouterOS 7.20 bridge engine forwarding soft lock"],
        safe_fix=["Upgrade off 7.20.", "If emergency recovery is needed, recreate the affected bridge during a maintenance window."],
        rollback=["Restore the old bridge config from export if recreation makes things worse.", "Return to prior known-good release if needed."],
        confirmed_hardware=["CRS3xx", "RouterOS bridge devices"],
        likely_hardware=["CCR", "RB5009"],
        not_relevant_on=["SwOS-only switching path"],
    ),
    "diagnose_dhcp_snooping_hw_offload_loss_qca8337_7_20": _tool(
        name="diagnose_dhcp_snooping_hw_offload_loss_qca8337_7_20",
        summary="Enabling DHCP snooping disables hardware offload on affected QCA8337/Atheros switch-chip platforms.",
        applies_to_versions="7.20-7.21.2",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "CPU load jumps after DHCP snooping enablement",
            "ports lose H flag or hardware forwarding behavior",
            "device uses QCA8337/Atheros switch-chip path",
        ],
        diagnostic_commands=[
            "/interface bridge port print detail",
            "/interface bridge settings print",
            "/tool profile",
            "/interface ethernet switch print",
        ],
        decision_tree=[
            "If device is CRS3xx using different silicon, this exact tool is weaker.",
            "If QCA8337/Atheros hardware loses offload only after DHCP snooping enablement, this matches the known issue.",
        ],
        likely_root_cause=["DHCP snooping disables or breaks expected hardware offload on QCA8337/Atheros in affected versions"],
        safe_fix=["Upgrade to 7.21.3 or later.", "If necessary, disable DHCP snooping temporarily on the affected platform."],
        rollback=["Re-enable prior bridge settings after upgrade validation.", "Restore snooping only after confirming H flag behavior."],
        fixed_in="7.21.3",
        confirmed_hardware=["QCA8337", "Atheros switch-chip platforms"],
        likely_hardware=["RB switch-chip devices"],
        not_relevant_on=["CRS3xx Marvell L2 path", "SwOS-only devices"],
    ),
    "diagnose_vlan_filtering_performance_regression_7_20": _tool(
        name="diagnose_vlan_filtering_performance_regression_7_20",
        summary="Complex VLAN-filtering setups show throughput or forwarding regression on 7.20-era bridge stack.",
        applies_to_versions="7.20-7.21.x",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "performance drops after upgrade with same topology",
            "complex bridge VLAN filtering path is in use",
            "no single subscriber issue explains the site-wide slowdown",
        ],
        diagnostic_commands=[
            "/interface bridge vlan print detail",
            "/interface bridge port print detail",
            "/tool profile",
            "/interface monitor-traffic <trunk>",
        ],
        decision_tree=[
            "If traffic is already CPU-punted by design, this tool may overfit.",
            "If the regression appears only after 7.20/7.21 with unchanged VLAN design, treat bridge performance regression as likely.",
        ],
        likely_root_cause=["RouterOS bridge VLAN filtering performance regression in complex setups"],
        safe_fix=["Upgrade to 7.22 or later.", "Simplify temporary bridge path only if upgrade is not immediately possible."],
        rollback=["Return to prior release if the new image causes unacceptable throughput collapse."],
        fixed_in="7.22",
        confirmed_hardware=["CRS3xx", "RouterOS bridge devices"],
        likely_hardware=["CCR", "RB5009"],
        not_relevant_on=["SwOS-only devices"],
    ),
    "diagnose_dynamic_switch_cpu_vlan_missing_7_20": _tool(
        name="diagnose_dynamic_switch_cpu_vlan_missing_7_20",
        summary="Expected dynamic switch-cpu VLAN entry is not created, breaking management or control-plane reachability.",
        applies_to_versions="7.20-7.20.x",
        bug_type="bug",
        impact="medium",
        invoke_when=[
            "management/control-plane access fails after VLAN bridge changes",
            "dynamic switch-cpu VLAN entry is expected but absent",
            "issue appears after upgrade or bridge rebuild on 7.20",
        ],
        diagnostic_commands=[
            "/interface bridge vlan print detail",
            "/interface bridge print detail",
            "/interface bridge port print detail",
        ],
        decision_tree=[
            "If the missing path is actually an operator-created static VLAN mistake, use the PVID/trunk tool instead.",
            "If the dynamic CPU-facing VLAN entry never appears on affected version, use this regression path.",
        ],
        likely_root_cause=["RouterOS 7.20 dynamic switch-cpu VLAN creation bug"],
        safe_fix=["Upgrade to 7.21 or later.", "Temporarily add the necessary VLAN membership explicitly if the platform/design allows it."],
        rollback=["Remove emergency static CPU VLAN membership after software fix if no longer needed."],
        fixed_in="7.21",
        confirmed_hardware=["RouterOS bridge hardware-offload devices"],
        likely_hardware=["CRS3xx"],
        not_relevant_on=["SwOS-only devices"],
    ),
    "diagnose_bridge_fast_path_crash_removed_interface_7_20": _tool(
        name="diagnose_bridge_fast_path_crash_removed_interface_7_20",
        summary="Removing a bridged interface under live traffic crashes or destabilizes fast-path forwarding.",
        applies_to_versions="7.20-7.20.x",
        bug_type="bug",
        impact="high",
        invoke_when=[
            "bridge datapath destabilizes right after interface removal",
            "live maintenance on bridged interface triggers crash-like symptoms",
            "problem aligns with fast-path/hardware-forwarding path",
        ],
        diagnostic_commands=[
            "/interface bridge port print detail",
            "/interface bridge settings print",
            "/log print where message~\"bridge|interface|fast\"",
            "/system resource print",
        ],
        decision_tree=[
            "If the outage was caused by removing the wrong trunk, this tool is not the right explanation.",
            "If the crash-like behavior only happens during live interface removal on affected versions, treat this as the known regression.",
        ],
        likely_root_cause=["RouterOS bridge fast-path instability when removing bridged interface under load"],
        safe_fix=["Upgrade to 7.21 or later.", "Perform interface removal only in controlled window on affected versions."],
        rollback=["Restore the removed port membership if recovery path permits.", "Return to known-good version if repeated."],
        fixed_in="7.21",
        confirmed_hardware=["RouterOS bridge devices"],
        likely_hardware=["CRS3xx", "CCR", "RB5009"],
        not_relevant_on=["SwOS-only devices"],
    ),
    "diagnose_pvid_access_trunk_misconfiguration_v6_to_v7": _tool(
        name="diagnose_pvid_access_trunk_misconfiguration_v6_to_v7",
        summary="Classic access-vs-trunk and PVID mismatch after RouterOS v6 to v7 bridge/VLAN migration.",
        applies_to_versions="7.x",
        bug_type="config_issue",
        impact="high",
        invoke_when=[
            "single edge port or customer path is wrong after migration",
            "untagged/tagged assumptions changed during v6 to v7 conversion",
            "port receives traffic but subscriber lands on wrong VLAN or no VLAN",
        ],
        diagnostic_commands=[
            "/interface bridge port print detail",
            "/interface bridge vlan print detail",
            "/interface bridge print detail",
            "/interface bridge host print",
        ],
        decision_tree=[
            "If the whole bridge is broken, use broader bridge regression tools first.",
            "If one port behaves like a trunk when it should be access, or vice versa, use this tool.",
        ],
        likely_root_cause=["PVID mismatch", "Port left tagged when it should be untagged", "v6 master-port era assumptions not cleanly converted"],
        safe_fix=["Correct PVID and tagged/untagged membership explicitly.", "Verify ingress filtering/frame-types policy matches the access design."],
        rollback=["Export bridge config before edits.", "Revert only the affected port memberships if needed."],
        confirmed_hardware=["CRS3xx", "CCR bridge", "RB5009 bridge"],
        likely_hardware=["Most RouterOS bridge-capable devices"],
        not_relevant_on=["SwOS-only config model"],
    ),
    "diagnose_hw_offload_enabled_but_cpu_forwarding": _tool(
        name="diagnose_hw_offload_enabled_but_cpu_forwarding",
        summary="Ports appear offloaded, but traffic still hits CPU. Diagnose the common bridge conditions that punt traffic out of hardware.",
        applies_to_versions="7.x",
        bug_type="config_pattern",
        impact="high",
        invoke_when=[
            "CPU load is too high for expected switched throughput",
            "operators think H flag means all traffic is offloaded",
            "performance suggests packets are hitting CPU despite offload expectations",
        ],
        diagnostic_commands=[
            "/interface bridge port print detail",
            "/interface bridge vlan print detail",
            "/tool profile",
            "/interface monitor-traffic <bridge-or-trunk>",
        ],
        decision_tree=[
            "If the hardware/platform never supported the target offload path, this is not a bug.",
            "If H flags exist but CPU remains hot, inspect features that punt traffic such as filtering, snooping, ACL-like features, multicast roles, or unsupported combinations.",
        ],
        likely_root_cause=["Feature combination disables true hardware forwarding", "Traffic class unsupported in offload path", "Bridge design assumption is wrong"],
        safe_fix=["Validate actual offload support matrix for the platform.", "Disable or redesign only the feature that forces CPU punt when operationally safe."],
        rollback=["Restore previous feature set if throughput or policy breaks after change."],
        confirmed_hardware=["CRS3xx", "RouterOS bridge hardware-offload devices"],
        likely_hardware=["CCR bridge roles", "RB5009 bridge roles"],
        not_relevant_on=["SwOS-only configs with separate semantics"],
    ),
    "diagnose_vlan_filtering_with_dhcp_snooping_support_matrix": _tool(
        name="diagnose_vlan_filtering_with_dhcp_snooping_support_matrix",
        summary="Determine whether the hardware/feature combination truly supports VLAN filtering plus DHCP snooping without CPU punt or breakage.",
        applies_to_versions="7.x",
        bug_type="config_support_matrix",
        impact="medium",
        invoke_when=[
            "operator wants both DHCP snooping and VLAN filtering on same bridge path",
            "current platform support is unclear",
            "enabling both features changes performance or behavior",
        ],
        diagnostic_commands=[
            "/interface bridge print detail",
            "/interface bridge settings print",
            "/interface bridge port print detail",
            "/tool profile",
        ],
        decision_tree=[
            "If the platform is SwOS, use SwOS-specific tools later.",
            "If bridge behavior changes only after enabling DHCP snooping alongside VLAN filtering, validate hardware support first instead of assuming a generic bridge bug.",
        ],
        likely_root_cause=["Unsupported or degraded feature combination on the given hardware path"],
        safe_fix=["Check actual platform support matrix before rollout.", "Use one-customer or one-switch pilot before broad deployment."],
        rollback=["Disable the newly added feature if it unexpectedly punts traffic or breaks forwarding."],
        confirmed_hardware=["RouterOS bridge hardware-offload platforms"],
        likely_hardware=["CRS3xx", "QCA/Atheros-based RouterOS devices"],
        not_relevant_on=["SwOS-specific implementation path"],
        confidence="medium",
    ),
    "diagnose_igmp_snooping_hw_offload_multicast_router_7_21": _tool(
        name="diagnose_igmp_snooping_hw_offload_multicast_router_7_21",
        summary="Multicast is not received when IGMP snooping and hardware offload are in use with multicast-router behavior. Known fix in 7.21.",
        applies_to_versions="7.20.x",
        bug_type="bug",
        impact="medium",
        invoke_when=[
            "multicast delivery breaks with IGMP snooping enabled",
            "bridge is acting as multicast-router or has multicast-router dependency",
            "issue is specific to multicast, not all traffic",
        ],
        diagnostic_commands=[
            "/interface bridge print detail",
            "/routing igmp-proxy print detail",
            "/interface bridge mdb print",
            "/tool sniffer quick multicast=yes",
        ],
        decision_tree=[
            "If multicast is broken because the upstream source is missing, this is not the right tool.",
            "If only multicast breaks on affected versions with snooping/offload path, prioritize this regression.",
        ],
        likely_root_cause=["IGMP snooping and hardware offload interaction around multicast-router behavior"],
        safe_fix=["Upgrade to 7.21 or later.", "If necessary, temporarily simplify multicast handling path during maintenance."],
        rollback=["Revert multicast-specific bridge changes if they worsen service."],
        fixed_in="7.21",
        confirmed_hardware=["RouterOS bridge multicast-capable platforms"],
        likely_hardware=["CRS3xx"],
        not_relevant_on=["Platforms with no multicast snooping role", "SwOS-only path"],
        confidence="medium",
    ),
    "diagnose_v6_to_v7_bridge_migration_breakage": _tool(
        name="diagnose_v6_to_v7_bridge_migration_breakage",
        summary="General v6 to v7 bridge migration trap: master-port era assumptions, VLAN conversion gaps, and non-equivalent defaults.",
        applies_to_versions="7.x after v6 migration",
        bug_type="migration_issue",
        impact="high",
        invoke_when=[
            "site broke only after v6 to v7 upgrade",
            "bridge/VLAN behavior differs despite seemingly similar config",
            "master-port style design existed before migration",
        ],
        diagnostic_commands=[
            "/export terse",
            "/interface bridge print detail",
            "/interface bridge port print detail",
            "/interface bridge vlan print detail",
        ],
        decision_tree=[
            "If the router was built natively on v7, use more specific bridge tools first.",
            "If the design was migrated from v6 and multiple edge assumptions changed, use this migration tool before chasing ghosts.",
        ],
        likely_root_cause=["v6 config model did not auto-convert cleanly to v7 bridge/VLAN model"],
        safe_fix=["Rebuild the intended bridge/VLAN design explicitly in v7 terms.", "Do not trust old master-port mental model."],
        rollback=["Keep pre-change export.", "Revert only after validating intended tagged/untagged design."],
        confirmed_hardware=["RouterOS bridge devices upgraded from v6"],
        likely_hardware=["CCR", "RB", "CRS running RouterOS"],
        not_relevant_on=["SwOS-only switches"],
    ),
    "diagnose_ra_guard_7_22_misconfiguration": _tool(
        name="diagnose_ra_guard_7_22_misconfiguration",
        summary="RA Guard is new in 7.22. Misconfiguration can break SLAAC on subscriber VLANs or block valid router advertisements.",
        applies_to_versions="7.22+",
        bug_type="feature_misconfiguration",
        impact="medium",
        invoke_when=[
            "IPv6 SLAAC breaks after enabling RA Guard",
            "subscriber VLANs stop receiving expected router advertisements",
            "issue begins after 7.22 hardening change",
        ],
        diagnostic_commands=[
            "/ipv6 nd print detail",
            "/interface bridge port print detail",
            "/tool sniffer quick ip-protocol=icmpv6",
        ],
        decision_tree=[
            "If the site does not use SLAAC or RA-based IPv6, this tool is low fit.",
            "If IPv6 onboarding breaks immediately after RA Guard enablement, inspect guard scope before changing upstream routing.",
        ],
        likely_root_cause=["RA Guard applied on the wrong edge/trunk path", "Valid RAs blocked by policy design mistake"],
        safe_fix=["Limit RA Guard to untrusted edge ports.", "Validate trusted RA source path before rollout."],
        rollback=["Disable RA Guard on the affected path if it blocks valid subscriber SLAAC behavior."],
        fixed_in="new in 7.22",
        confirmed_hardware=["RouterOS 7.22+ bridge-capable devices"],
        likely_hardware=["CRS3xx", "CCR", "RB5009"],
        not_relevant_on=["IPv4-only access designs", "SwOS-only path"],
    ),
    "diagnose_mvrp_vlan_propagation_breakage": _tool(
        name="diagnose_mvrp_vlan_propagation_breakage",
        summary="MVRP configuration or upgrade drift causes VLAN propagation to stop. Pre-7.22 WinBox disable path is also problematic.",
        applies_to_versions="7.x, especially pre-7.22",
        bug_type="feature_misconfiguration",
        impact="medium",
        invoke_when=[
            "VLAN propagation unexpectedly stops on MVRP-enabled design",
            "issue appears after upgrade or GUI-side MVRP change",
            "dynamic VLAN advertisements no longer populate as expected",
        ],
        diagnostic_commands=[
            "/interface bridge print detail",
            "/interface bridge vlan print detail",
            "/interface bridge port print detail",
        ],
        decision_tree=[
            "If MVRP is not intentionally used, this is not the right tool.",
            "If VLAN presence depends on MVRP and disappears after upgrade/change, inspect MVRP state and management path first.",
        ],
        likely_root_cause=["MVRP configuration drift", "Pre-7.22 disable path problem", "Dynamic VLAN propagation state lost"],
        safe_fix=["Validate MVRP intent explicitly.", "Prefer CLI-side verification and upgrade to 7.22+ if disable/reenable behavior is suspect."],
        rollback=["Restore previous static VLAN memberships if MVRP rollback is needed."],
        fixed_in="WinBox disable issue improved in 7.22",
        confirmed_hardware=["RouterOS bridge devices using MVRP"],
        likely_hardware=["CRS3xx"],
        not_relevant_on=["Sites not using MVRP", "SwOS-only path"],
        confidence="medium",
    ),
}


def scenario_tool_names() -> list[str]:
    return list(ROUTEROS_SWITCHING_SCENARIOS.keys())
